---
###############################################################################
# Pi-Hole Install
###############################################################################
# RedHat specific installation options.
#
# Firewall changes are applied based on default firewalls settings.
#
# All RedHat issues should be assigned to: @rkoosaar
#
# Reference:
# * https://github.com/r-pufky/ansible_pihole/issues/10

- name: 'RedHat Support is Best Effort!'
  ansible.builtin.debug:
    msg: |
      RedHat support is currently best effort.

      https://github.com/r-pufky/ansible_pihole/issues/10

- name: 'Redhat | install dependencies'
  ansible.builtin.dnf:
    name:  '{{ pihole_default_packages_rpm }}'
    state: 'latest'
    update_cache: true

- name: 'Redhat | set SELinux to permissive'
  ansible.builtin.lineinfile:
    path:   '/etc/sysconfig/selinux'
    regexp: '^SELINUX=enforcing'
    line:   'SELINUX=permissive'
    state:  'present'

- name: 'Redhat | enable pihole traffic in default zone'
  ansible.posix.firewalld:
    zone:    'FedoraServer'
    service: '{{ item }}'
    permanent: true
    state:   'enabled'
  loop:
    - 'http'
    - 'dns'
    - 'dhcp'
    - 'dhcpv6'

- name: 'Redhat | create pihole firewalld zone'
  ansible.posix.firewalld:
    zone:  'pihole'
    state: 'present'
    permanent: true

- name: 'Redhat | add local interface for pihole ftl service'
  ansible.posix.firewalld:
    zone:  'pihole'
    interface: 'lo'
    permanent: true
    state: 'enabled'

- name: 'Redhat | enable ftl traffic to local interface'
  ansible.posix.firewalld:
    zone:  'pihole'
    port:  '4711/tcp'
    permanent: true
    state: 'enabled'
